config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users
  get "rentals-request/new", to: "rentals#new"
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  get "/profile", to: "users#show"
  resources :restaurants, only: %i[destroy]
  resources :restaurants, only: %i[index show edit update new create] do
    resources :rentals, only: %i[new create]
  end

  resources :rentals do
    member do
      patch :accept
    end
  end

  resources :rentals do
    member do
      patch :decline
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/rental.rb
class Rental < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant

  validates :reservation_date, presence: true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  CATEGORY = ["Bar", "Boteco", "Buffet", "Restaurante", "Quiosque", "Rodízio"]

  validates :name, :location, :address, :category, presence: true
  validates :category, inclusion: { in: CATEGORY }

  belongs_to :user
  has_many :rentals, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  has_many :restaurants, dependent: :destroy
  has_many :rentals, dependent: :destroy
  has_many :rents_as_owner, through: :restaurants, source: :rentals
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit::Authorization

  # Uncomment when you *really understand* Pundit!
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  def user_not_authorized
    flash[:alert] = "You are not authorized to access."
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  before_action :set_restaurant, only: %i[new create]

  def new
    @rental = Rental.new
  end

  def create
    @rental = Rental.new(rental_params)
    @rental.restaurant = @restaurant
    @rental.user = current_user
    @rental.status = "pending"
    if @rental.save
      redirect_to restaurants_path
    else
      render :new
    end
  end

  def accept
    # find rental by id
    @rental = Rental.find(params[:id])
    # update status to accepted
    @rental.status = "accepted"
    if @rental.save
      flash[:notice] = "Reservation accepted"
      redirect_to profile_path
    end
  end

  def decline
    # find rental by id
    @rental = Rental.find(params[:id])
    # update status to accepted
    @rental.status = "declined"
    if @rental.save
      flash[:notice] = "Reservation declined"
      redirect_to profile_path
    end
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def rental_params
    params.require(:rental).permit(:reservation_date)
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]
  before_action :set_restaurant, only: %i[show edit update destroy]

  # Pundit: allow-list approach
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  def index
    @restaurants = policy_scope(Restaurant)
  end

  def show
    @user = current_user if user_signed_in?
    @rental = Rental.new
  end

  def new
    @restaurant = Restaurant.new
    authorize @restaurant
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.user = current_user
    authorize @restaurant

    if @restaurant.save
      redirect_to restaurant_path(@restaurant), notice: "Restaurant was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @restaurant.update(restaurant_params)
      redirect_to restaurant_path(@restaurant), notice: "Restaurant updated", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_url, notice: "Restaurant deleted", status: :see_other
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :location, :address, :category, :description)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
    authorize @restaurant
  end

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
    @restaurant = Restaurant.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Magic Table</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/rentals/_new.html.erb
<h3>Make your reservation</h3>
  <%= simple_form_for ([@restaurant, @rental]) do |f| %>
    <%= f.input :reservation_date, as: :string, input_html: { data: { controller: "datepicker" } } %>
    <%= f.button :submit, class: "btn btn-primary" %>
  <% end %>

app/views/rentals/new.html.erb
<div class="container col-12 mt-4">
<h3>Make your reservation</h3>
  <%= simple_form_for ([@restaurant, @rental]) do |f| %>
    <%= f.input :reservation_date %>
    <%= f.button :submit, class: "btn btn-primary" %>
  <% end %>

  <div class="return row mt-3">
    <%= link_to restaurant_path(@restaurant) do %>
      <p><i class="fa-solid fa-rotate-left "></i>Back to restaurant</p>
    <% end %>
  </div>
</div>

app/views/restaurants/_form.html.erb
<div class="col-6">
  <%= simple_form_for restaurant do |f| %>
    <%= f.input :name %>
    <%= f.input :location %>
    <%= f.input :address %>
    <%= f.input :category, collection: Restaurant::CATEGORY %>
    <%= f.input :description %>
    <%= f.submit action_text: "Add Restaurant", class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/restaurants/_restaurant.html.erb
<div class="info">
  <p>Address: <%= restaurant.address %></p>
  <p>Location: <%= restaurant.location %></p>
  <p>Category: <%= restaurant.category %></p>
  <p>Description: <%= restaurant.description %></p>
  <p>User e-mail: <%= restaurant.user.email %></p>
</div>

app/views/restaurants/edit.html.erb
<h1>Edit Restaurant</h1>
<%= render "form", restaurant: @restaurant, action_text: "Edit Restaurant" %>

<div class="return row mt-3">
  <%= link_to restaurant_path(@restaurant) do %>
    <p><i class="fa-solid fa-rotate-left "></i>Back to restaurant</p>
  <% end %>
</div>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>

<div id="restaurants">
  <ul>
    <% @restaurants.each do |restaurant| %>
      <li><%= link_to restaurant.name, restaurant_path(restaurant) %></li>
    <% end %>
  </ul>
</div>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>
<%= render "form", restaurant: @restaurant, action_text: "Create Restaurant" %>

<div class="return row mt-3">
  <%= link_to restaurants_path do %>
    <p><i class="fa-solid fa-rotate-left "></i>Back to restaurants</p>
  <% end %>
</div>

app/views/restaurants/show.html.erb
<h1><strong><%= @restaurant.name %></strong></h1>

<%= render @restaurant %>

<% if user_signed_in? && @restaurant.user != @user %>
  <%= render 'rentals/new' %>
<% end %>

<div id="navbuttons">
  <% if policy(@restaurant).edit? %>
    <%= link_to edit_restaurant_path(@restaurant) do %>
      <p><i class="fa-solid fa-pen"></i>Edit restaurant</p>
    <% end %>
  <% end %>

  <% if policy(@restaurant).destroy? %>
    <%= link_to restaurant_path(@restaurant),
              method: :delete,
              data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } do %>
      <p><i class="fa-solid fa-trash"></i>Delete restaurant</p>
    <% end %>
  <% end %>

  <%= link_to restaurants_path do %>
    <p><i class="fa-solid fa-rotate-left"></i>Back to restaurants</p>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "Restaurants", restaurants_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Profile", profile_path, class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h1>Profile Page</h1>
<p>E-mail: <%= @user.email %></p>

<div>
  <% @user.rents_as_owner.each do |rent| %>

    <p>Restaurant: <%= rent.restaurant.name %> - <%= rent.restaurant.location %></p>
    <p>Reservation date: <%= rent.reservation_date %></p>
    <p>Client e-mail: <%=rent.user.email%></p>
    <p>Status: <u><%= rent.status %></u></p>

    <% if rent.status == "pending" %>

      <div>
        <%= button_to "Accept", accept_rental_path(rent), method: :patch, class: "btn btn-primary" %>
        <%= button_to "Decline", decline_rental_path(rent), method: :patch, class: "btn btn-danger", style: "margin-left: 10px;" %>
      </div>
    <% end %>
  <% end %>

  <div>
    <h2>Your restaurants</h2>
  </div>
  <div>
    <% @user.restaurants.each do |restaurant| %>
      <p>Name: <%= restaurant.name %></p>
      <p>Location: <%= restaurant.location %></p>
      <p>Address: <%= restaurant.address %></p>
    <% end %>
  </div>

  <div data-controller="toggle">
    <button data-action="click->toggle#interact" class="btn btn-outline-primary">Add New Restaurant</button>
    <div data-toggle-target="togglableElement" class="d-none">
      <%= render "restaurants/form", restaurant: @restaurant  %>
    </div>
  </div>
</div>